name: Lighthouse-CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli
      - name: Run Lighthouse
        env:
          LHCI_BUILD_CONTEXT__CURRENT_BRANCH: ${{ github.head_ref || github.ref_name }}
        run: |
          lhci autorun --config lighthouserc.json