task_id: claude_parity_alignment_2025_05
title: Align Claude Behavioral Parity with Pulser v1.1.1
objective: Ensure Claude agent reaches full behavioral parity with Pulser v1.1.1 feature set as defined in `claude_parity_matrix.yaml`.
priority: high
created_date: 2025-05-04
target_completion: 2025-05-07T18:00:00+08:00

subtasks:
  - code: T1
    description: Review all ❌ (failed) and ⚠️ (partial) features from diagnostic script
    owner: Claudia
    status: pending
    
  - code: T2
    description: Implement missing feature - Context Snapshot Save/Restore
    owner: DevOps
    status: partial
    
  - code: T3
    description: Implement missing feature - Session ID Persistence
    owner: Backend
    status: missing
    
  - code: T4
    description: Improve Error Boundary Reporting to match Claude CLI behavior
    owner: Susi
    status: missing
    
  - code: T5
    description: Rerun `pulser-claude-compare.sh` and sync updated parity matrix
    owner: Claudia
    status: queued
    
  - code: T6
    description: Auto-sync updated matrix to Kalaw and Claudia dashboards
    owner: Kalaw
    status: queued
    
  - code: T7
    description: Log update to `/logs/claude_parity_test.log` and JSON export
    owner: Claudia
    status: pending

files_involved:
  - ~/.pulser/config/claude_parity_matrix.yaml
  - tools/pulser-claude-compare.sh
  - router/index.js

dependencies:
  - T1 must complete before T5
  - T2, T3, T4 can run in parallel
  - T5 must complete before T6
  - T6 must complete before T7

agent_assignments:
  claudia:
    - T1
    - T5
    - T7
  devops:
    - T2
  backend:
    - T3
  susi:
    - T4
  kalaw:
    - T6

testing:
  script: tools/pulser-claude-compare.sh
  log_output: ~/.pulser/logs/claude_parity_test.log
  schedule: daily
  notification: slack
  
metrics:
  target_parity_score: 95
  current_parity_score: 70
  improvement_goal: 25
  
notes: >
  This task focuses on closing the behavioral parity gaps between Claude and Pulser v1.1.1.
  Special attention should be given to error handling and session persistence to match
  the Claude Code CLI experience.