name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: scout-dashboard-prod
  AZURE_FUNCTIONAPP_NAME: scout-api-prod

jobs:
  check-deployment-ready:
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.check.outputs.should_deploy }}
    steps:
      - name: Check if Azure credentials exist
        id: check
        run: |
          if [ -n "${{ secrets.AZURE_CREDENTIALS }}" ]; then
            echo "should_deploy=true" >> $GITHUB_OUTPUT
            echo "✅ Azure credentials found, deployment will proceed"
          else
            echo "should_deploy=false" >> $GITHUB_OUTPUT
            echo "⚠️ Azure credentials not configured. Skipping deployment."
            echo "To enable deployment, add the following secrets in GitHub:"
            echo "  - AZURE_CREDENTIALS"
            echo "  - AZURE_STATIC_WEB_APPS_API_TOKEN_PROD"
            echo "  - AZURE_FUNCTIONAPP_PUBLISH_PROFILE_PROD"
          fi

  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    needs: check-deployment-ready
    if: needs.check-deployment-ready.outputs.should_deploy == 'true'
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install and build frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/frontend"
          api_location: ""
          output_location: "dist"

  build-and-deploy-backend:
    runs-on: ubuntu-latest
    needs: check-deployment-ready
    if: needs.check-deployment-ready.outputs.should_deploy == 'true'
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install and build backend
        working-directory: ./backend
        run: |
          npm ci
          npm run build

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ./backend
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_PROD }}

      - name: Run smoke tests
        run: |
          sleep 30
          curl -f https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net/api/health || exit 1